#spring:
#    profiles: dev
#    datasource:
#        type: com.alibaba.druid.pool.DruidDataSource
#        master:
#           name: test
#           url: jdbc:mysql://119.23.55.190:3306/hsd?useSSL=false
#           username: root
#           password: 1234
#           driver-class-name: com.mysql.jdbc.Driver
#           filters: stat
#           maxActive: 20
#           initialSize: 1
#           maxWait: 60000
#           minIdle: 1
#           timeBetweenEvictionRunsMillis: 60000
#           minEvictableIdleTimeMillis: 300000
#           validationQuery: select 'x' FROM DUAL
#           testWhileIdle: true
#           testOnBorrow: false
#           testOnReturn: false
#           poolPreparedStatements: true
#           maxOpenPreparedStatements: 20
spring:
  aop:
    proxy-target-class: true
  application:
    name: teachinginteraction
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.134.1:3306/graduation?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

mapper:
    mappers: tk.mybatis.mapper.common.Mapper
    identity: select sys_guid() from dual
    order: before
---
########################################################
###THYMELEAF (ThymeleafAutoConfiguration)
########################################################
spring:
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        mode: LEGACYHTML5
        encoding: UTF-8
        cache: false
        cache-period: 0

---
server:
  port: 8001
  session-timeout: 30
  ##tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

logging:
  level:
     com.lzc.teachingInteraction : info
#上传文件大小不限制
 # spring.servlet.multipart.max-file-size=-1
  #spring.servlet.multipart.max-request-size=-1
spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    cache: false

mybatis:
  type-aliases-package: com.lzc.teachingInteraction.entity
  mapper-locations: classpath:com.lzc.teachingInteraction.mapper/*.xml
